title: Book reviews of Prasanna
email: prasannacse2005@gmail.com
description: I was reading books for sometime and I want a place to review the books which I read. I can use this place for it.
baseurl: "book"
url: "http://worldofprasanna.in" # the base hostname & protocol for your site
twitter_username: prasannacse2005
github_username:  worldofprasanna

# Build settings
markdown: kramdown
